security:
    providers:
        oidc_user_provider:
            id: App\Security\OidcUserProvider

    firewalls:
        main:
            lazy: true
            custom_authenticator: App\Security\OidcAuthenticator
            stateless: false
            logout:
                path: app_logout
                target: /home
            # No "anonymous" option needed; anonymous users are allowed by default

    access_control:
        # Require authentication for /api
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
