# config/packages/dev/web_profiler.yaml
web_profiler:
    toolbar: true       # Enable the toolbar displayed at the bottom of the browser
    intercept_redirects: false # Set to true if you want to see redirects in the toolbar

framework:
    profiler:
        only_exceptions: false # Collect all requests, not just exceptions
        collect: true          # Enable the profiler collection